---
# tasks file for apache
- name: Install latest version of Apache
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: true

- name: Create document root for domain configured in host variable
  ansible.builtin.file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Copy your index file
  ansible.builtin.template:
    src: "index.html.j2"
    dest: "/var/www/{{ http_host }}/index.html"
    mode: '0755'

- name: Set up Apache virtualhost
  ansible.builtin.template:
    src: "apache.conf.j2"
    dest: "/etc/apache2/sites-available/{{ http_conf }}"
    mode: '0755'

- name: Enable site
  ansible.builtin.command: a2ensite {{ http_conf }}
  notify: Reload apache
  register: service_enable
  changed_when: service_enable != 0

- name: Disable default Apache site
  ansible.builtin.command: a2dissite 000-default.conf
  notify: Reload apache
  register: service_reload
  changed_when: service_reload != 0
